version: '3.8'

services:
  curves-app:
    build: .
    container_name: curves-streamlit
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Shanghai # 给容器设定正确的时区
      # 允许 Cloudflare 进行跨域请求
      - STREAMLIT_SERVER_ENABLE_CORS=false
      # 关闭 CSRF 验证（否则通过隧道可能会白屏）
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=false
      # 【关键参数】允许来自 Cloudflare 的网页代理转发
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
